import MainHeader from '@/components/shared/MainHeader';
import MainFooter from '@/components/shared/MainFooter';

import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const RootLayout = ({ children }) => (
	<html lang="en">
		<body>
			<div className="main-container">
				<MainHeader/>
				{children}
				{/* <MainFooter/> */}
			</div>
		</body>
	</html>
);

export default RootLayout;